language: php
sudo: false
php:
- 7
- 5.6
- 5.5
- hhvm
matrix:
  fast_finish: true
  allow_failures:
  - php: hhvm
env:
  global:
  - PATH="$PATH:$HOME/.composer/vendor/bin"
  - DRUPAL_TI_MODULE_NAME="discussions"
  - DRUPAL_TI_SIMPLETEST_GROUP="discussions"
  - DRUPAL_TI_ENVIRONMENT="drupal-8"
  - DRUPAL_TI_CORE_BRANCH="8.3.x"
  - DRUPAL_TI_DB="drupal_travis_db"
  - DRUPAL_TI_DB_URL="mysql://root:@127.0.0.1/drupal_travis_db"
  - DRUPAL_TI_WEBSERVER_URL="http://127.0.0.1"
  - DRUPAL_TI_WEBSERVER_PORT="8080"
  - DRUPAL_TI_SIMPLETEST_ARGS="--verbose --color --concurrency 4 --url $DRUPAL_TI_WEBSERVER_URL:$DRUPAL_TI_WEBSERVER_PORT"
  - DRUPAL_TI_BEHAT_DIR="./tests/behat"
  - DRUPAL_TI_BEHAT_ARGS=""
  - DRUPAL_TI_BEHAT_YML="behat.yml.dist"
  - DRUPAL_TI_BEHAT_SCREENSIZE_COLOR="1280x1024x16"
  - DRUPAL_TI_BEHAT_SELENIUM_VERSION="2.48.2"
  - DRUPAL_TI_BEHAT_DRIVER="phantomjs"
  - DRUPAL_TI_BEHAT_BROWSER="firefox"
  - DRUPAL_TI_PHPUNIT_ARGS=""
  - DRUPAL_TI_COVERAGE="satooshi/php-coveralls:0.6.*"
  - DRUPAL_TI_COVERAGE_FILE="build/logs/clover.xml"
  matrix:
  - DRUPAL_TI_RUNNERS="phpunit-core"
mysql:
  database: drupal_travis_db
  username: root
  encoding: utf8
before_install:
- phpenv config-rm xdebug.ini || true
- composer self-update
- composer global require "hirak/prestissimo:^0.3"
- composer global require "lionsad/drupal_ti:dev-master"
- composer global require "squizlabs/php_codesniffer:2.*"
- composer global require "drupal/coder:8.2.*"
- phpcs --config-set installed_paths $HOME/.composer/vendor/drupal/coder/coder_sniffer
- phpcs --standard=Drupal $TRAVIS_BUILD_DIR
- drupal-ti before_install
install:
- drupal-ti install
before_script:
- drupal-ti before_script
script:
- drupal-ti script
after_script:
- drupal-ti after_script
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    secure: Uy7MUep/mj6LBQlusNojRI1DTYV0BLJnVlJ+y+PAMo1fLLs1DjkkaMiHgICO/7P2QdamAzxNYmoIJB6IQYEjTHjcS9q9fZmMIxby/KV0tmqnAjYzEdB3jQSnoj+zyes9Grict3p+SspWwRqa1rBpdaGD3AF9ProPtPm5q3GFoAGV4xTbWNFHyb12S4N6y23egvQQKoqBvdBnV+FthBETl2rKOzlZVpjNpB5pN4jvWqjX2gHUpJD4Q7viGmuUY3FYjvCh0a+z+dkzLrgIk7HZDuTqBL4tI76bYhWfyjrUuW+fxnYqKJEHVlxfC5VGRimdiI/ECZcD/tgMV0wcV/8Hc+R+4yTbXL1UKb+Pq9ftAeEE0fCZi214+I+GKcOwjaczB12GM540PJMQS1EbhyC5azUREfXq8vdWBZW1h86HQGPMq6qh2bm35L8XoGrPl0GabQ+vI1xk29RNARHsWrMcBQqO6yUk2N1S0xCYTW0ME60jCOw7RVzgq12YPpUqs4S3OkRwfG/DCnfgPnrfhEXDSGeDdf+aJqPOvBmaHC6MogOsz7yHBbssWX5ubzscRzNJeNYMyFJ6QloeFk4T//udedDqAos//WzRRpMgaCPikMwRkwt9yYet3HLlJN+29vNRSSTZ+YoQEvwunHzFRWohfKmIUz9I4KhQSq6Wi/Acfuc=
