<?php

/**
 * @file
 * Adds discussion groups to Drupal.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\group\Entity\GroupType;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;
use Drupal\views\Views;

/**
 * Implements hook_entity_type_alter().
 */
function discussions_entity_type_alter(array &$entity_types) {
  $entity_types['discussion']->setFormClass('discussion-form', 'Drupal\discussions\Form\GroupDiscussionFormStep1');
  $entity_types['group_content']->setFormClass('discussion-form', 'Drupal\discussions\Form\GroupDiscussionFormStep2');
}

/**
 * Implements hook_theme().
 */
function discussions_theme() {
  $theme = [];

  $theme['discussions_discussion_add_list'] = array(
    'render element' => 'content',
    'variables' => array('content' => NULL),
    'file' => 'discussions.page.inc',
  );

  return $theme;
}

/**
 * Implements hook_entity_extra_field_info().
 */
function discussions_entity_extra_field_info() {
  $extra = array();

  foreach (GroupType::loadMultiple() as $group_type) {
    // Add discussions field to group entity.
    $extra['group'][$group_type->id()]['display']['discussions'] = array(
      'label' => t('Discussions'),
      'description' => t('List of discussions in group.'),
      'weight' => 100,
      'visible' => TRUE,
    );
  }

  return $extra;
}

/**
 * Implements hook_entity_view_alter().
 */
function discussions_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  // Add fields to group entity.
  if (isset($build['#entity_type']) && ($build['#entity_type'] == 'group')) {
    // Populate discussions field.
    $build['discussions'] = array(
      '#type' => 'view',
      '#name' => 'discussions_group_discussions',
      '#display_id' => 'default',
      '#arguments' => array($entity->id()),
    );
  }
}

/**
 * Implements hook_views_query_alter().
 */
function discussions_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() == 'discussions_group_discussions') {

    // Include comments when searching discussions.
    $comment_field_data_config = array(
      'type' => 'LEFT',
      'table' => 'comment_field_data',
      'field' => 'entity_id',
      'left_table' => 'discussions',
      'left_field' => 'id',
      'operator' => '=',
      'extra' => array(
        0 => array(
          'field' => 'comment_type',
          'value' => 'discussions_reply',
        ),
      ),
    );

    $comment_body_config = array(
      'type' => 'LEFT',
      'table' => 'comment__comment_body',
      'field' => 'entity_id',
      'left_table' => 'comment_field_data',
      'left_field' => 'cid',
      'operator' => '=',
      'extra' => array(
        0 => array(
          'field' => 'deleted',
          'value' => 0,
        ),
      ),
    );

    // Join comment_field_data table.
    $comment_field_data_join = Views::pluginManager('join')->createInstance('standard', $comment_field_data_config);
    // Add comment_field_data table relationship so comment__comment_body
    // table can be joined.
    $query->addRelationship('comment_field_data', $comment_field_data_join, 'comment_field_data');

    // Join comment__comment_body table.
    $comment_body_join = Views::pluginManager('join')->createInstance('standard', $comment_body_config);
    $query->addTable('comment__comment_body', 'comment_field_data', $comment_body_join);

    if (!empty($query->view->filter['combine']->value)) {
      // The where group containing the discussion match condition.
      $where_group = 1;

      // Change the where group from AND to OR to accept two conditions.
      $query->where[$where_group]['type'] = 'OR';

      // Add comment body match condition.
      $query->addWhere($where_group,
        'comment_field_data__comment__comment_body.comment_body_value',
        '%' . $query->view->filter['combine']->value . '%',
        'LIKE');
    }
  }
}

/**
 * Implements hook_views_data_alter().
 */
function discussions_views_data_alter(&$data) {

  $data['discussions']['current_user'] = array(
    'title' => t('Discussions by current user'),
    'filter' => array(
      'title' => t('Discussions by current user'),
      'help' => t('Filters discussions by the current user.'),
      'field' => 'user',
      'id' => 'discussions_current_user'
    ),
  );

}
