<?php

/**
 * @file
 * Adds discussion groups to Drupal.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\group\Entity\GroupType;

/**
 * Implements hook_entity_type_alter().
 */
function discussions_entity_type_alter(array &$entity_types) {
  $entity_types['discussion']->setFormClass('discussion-form', 'Drupal\discussions\Form\GroupDiscussionFormStep1');
  $entity_types['group_content']->setFormClass('discussion-form', 'Drupal\discussions\Form\GroupDiscussionFormStep2');
}

/**
 * Implements hook_theme().
 */
function discussions_theme() {
  $theme = [];

  $theme['discussions_discussion_add_list'] = array(
    'render element' => 'content',
    'variables' => array('content' => NULL),
    'file' => 'discussions.page.inc',
  );

  return $theme;
}

/**
 * Implements hook_entity_extra_field_info().
 */
function discussions_entity_extra_field_info() {
  $extra = array();

  foreach (GroupType::loadMultiple() as $group_type) {
    // Add discussions field to group entity.
    $extra['group'][$group_type]['display']['discussions'] = array(
      'label' => t('Discussions'),
      'description' => t('List of discussions in group.'),
      'weight' => 100,
      'visible' => TRUE,
    );
  }

  return $extra;
}

/**
 * Implements hook_entity_view_alter().
 */
function discussions_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  // Add fields to group entity.
  if (isset($build['#entity_type']) && ($build['#entity_type'] == 'group')) {
    // Populate discussions field.
    $build['discussions'] = array(
      '#type' => 'view',
      '#name' => 'discussions_group_discussions',
      '#display_id' => 'default',
      '#arguments' => array($entity->id()),
    );
  }
}
