# Schema for the configuration files of the discussions module.

discussions.discussion_type.*:
  type: config_entity
  label: 'Discussion Type'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    uid:
      type: integer
      label: 'User ID'
