<?php

/**
 * @file
 * Contains discussions_email.module..
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\discussions\Entity\Discussion;
use Drupal\user\Entity\User;

define('DISCUSSIONS_EMAIL_FREQUENCY_NONE', 1);
define('DISCUSSIONS_EMAIL_FREQUENCY_INDIVIDUAL', 2);
define('DISCUSSIONS_EMAIL_FREQUENCY_DIGEST', 3);

define('DISCUSSION_GROUP_EMAIL_SEPARATOR', '+');

/**
 * Implements hook_help().
 */
function discussions_email_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the discussions_email module.
    case 'help.page.discussions_email':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Create discussions by sending emails.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_insert().
 */
function discussions_email_group_type_insert(EntityInterface $entity) {
  // TODO: Add discussions_email_address field automatically.
}

/**
 * Implements hook_entity_insert().
 */
function discussions_email_group_content_type_insert(EntityInterface $entity) {
  /** @var \Drupal\group\Entity\GroupContentType $entity */
  if ($entity->getContentPlugin() == 'group_membership') {
    // TODO: Add discussions_email_frequency field automatically.
  }
}

/**
 * Implements hook_entity_insert().
 */
function discussions_email_comment_insert(EntityInterface $entity) {
  /** @var \Drupal\comment\Entity\Comment $entity */

  // Only send email if comment is a reply to a discussion.
  if ($entity->bundle() != 'discussions_reply') {
    return;
  }

  // Load comment author user.
  $user = User::load($entity->get('uid')->getValue());

  // Load parent discussion.
  $discussion = $entity->getCommentedEntity();

  /** @var \Drupal\discussions\GroupDiscussionService $group_discussion_service */
  $group_discussion_service = \Drupal::service('discussions.group_discussion');

  // Load group containing parent discussion.
  $group = $group_discussion_service->getDiscussionGroup($discussion->id());

  $to_addresses = [];

  // Select group members to send email update to.
  foreach ($group->getMembers() as $member) {
    // Skip unapproved group members.
    if ($member->requiresApproval()) {
      continue;
    }

    if ($member->getGroupContent()->hasField('discussions_email_frequency')) {
      $email_frequency = $member->getGroupContent()->get('discussions_email_frequency')->value;

      // Skip members who choose not to receive individual updates.
      if ($email_frequency != DISCUSSIONS_EMAIL_FREQUENCY_INDIVIDUAL) {
        continue;
      }

      $to_addresses[] = $member->getUser()->getEmail();
    }
  }

  // TODO: Only send to comment author if configured in group settings.

  // Only send email if there's at least one valid recipient.
  if (empty($to_addresses)) {
    return;
  }

  // Get ID of the currently enabled discussions email plugin.
  $config = \Drupal::config('discussions_email.settings');
  $email_plugin_id = $config->get('discussions_email_plugin_id');

  // Don't attempt to send email without an enabled plugin.
  if (empty($email_plugin_id)) {
    return;
  }

  /** @var \Drupal\discussions_email\DiscussionsEmailPluginManager $email_plugin_manager */
  $email_plugin_manager = \Drupal::service('plugin.manager.discussions_email');

  /** @var \Drupal\discussions_email\Plugin\DiscussionsEmailPluginInterface $plugin */
  $plugin = $email_plugin_manager->createInstance($email_plugin_id);

  // Send email via plugin.
  $group_email_address = $group->get('discussions_email_address')->value;
  list($from_user, $from_domain) = explode('@', $group_email_address);
  $from_address = $from_user . DISCUSSION_GROUP_EMAIL_SEPARATOR . $group->id() . DISCUSSION_GROUP_EMAIL_SEPARATOR . $entity->id() . '@' . $from_domain;

  // TODO: Postscript token replacement on body.
  $body = $entity->get('comment_body')->value;

  $message = [
    // TODO:
    'id' => '',
    'from_name' => '',
    'from_email' => $from_address,
    'to' => $to_addresses,
    'subject' => $discussion->label(),
    'body' => $body,
  ];

  $plugin->sendEmail($message, $group, $discussion);
}
